all: hello hello2 valsem
	g++ -o hello hello.cpp -std=c++11

hello: hello.cpp
	g++ -o hello hello.cpp -std=c++11

hello2: hello2.cpp
	g++ -o hello2 hello2.cpp -std=c++11

valsem: valsem.cpp
	g++ -o valsem valsem.cpp -std=c++11